export const ActionTypes = {
  LOAD_CART: "LOAD_CART",
  LOAD_FAV: "LOAD_FAV",
  REMOVE_CART: "DELETE_CART",
  REMOVE_FAV: "REMOVE_FAV",
  ADD_CART: "ADD_CART",
  ADD_FAV: "ADD_FAV",
  CLEAR_CART: "CLEAR_CART",
  CLEAR_FAV: "CLEAR_FAV",
  INCREASE_CART:"INCREASE_CART",
  DECREASE_CART:"INCREASE_CART",
};
